### ISSUE TITLE
[help] Slide Paragraph Breaks Symbol doesn,t work

### ISSUE THREAD

**Issue by fan9704** [jackey8616/hexo-generator-slidehtml#5]
Slide Paragraph Breaks Symbol 

```
---

page 1

----

page 1.1

----

page 1.2

```

My Global Hexo Configuration

```yaml
slidehtml:
  titleMerge: true
  horizontalSeparator: '---'
  verticalSeparator: '----'
  slideTransition: none
```

It will display in different paragraph 
It should display in same paragraph and different page my configuration is wrong?

**Comment by fan9704** [comment]
Ok I Got it my fault

```yaml
slidehtml:
  titleMerge: true
  horizontalSeparator: '----'
  verticalSeparator: '---'
  slideTransition: none
  
  ```
  
  I configure it as a opposite way xd
